name: First Workflow
on: push
jobs:
    first_job:
        name: first job
        runs-on: ubuntu-latest
        steps:
            - name: Try Echo
              run: echo "Welcome to my first job"

            - name: Print the path
              run: pwd

            - name: Checkout
              uses: actions/checkout@v4

            - name: Print Content of Readme file
              run: cat README.md