name: Multiple Jobs Workflow
on: push
env:
    USER: Devendra
jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: print something from env
              run: echo "Printing user- ${{ env.USER }}"

            - name: Creating a file
              run: echo "This if my file" >> myfile.txt

            - name: Upload File
              uses: actions/upload-artifact@v4
              with:
                name: myfile
                path: ./myfile.txt
    
    job-2:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Running the script 
              run:  |
                chmod +x custom.sh
                sh custom.sh
              
    job-3:
        runs-on: ubuntu-latest
        needs: [job-1, job-2]
        steps:
            - name: Generating Dependencies
              run: echo "This is ran after job-1 and job-2 are finished" 
            
            - name: Value From Settings
              run: |
                echo "Secret Value is ${{ secrets.MY_SECRET}}"
                echo "Variable is ${{ vars.MY_VAR}}"

            - name: Downloading File
              uses: actions/download-artifact@v4
              with:
                name: myfile
                path: ./myfile.txt

            - name: Printing File Content
              run: cat ./myfile.txt