name: Multiple Jobs Workflow
on: push
env:
    USER: Devendra
jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: print something from env
              run: echo "Printing user- ${{ env.USER }}"
    
    job-2:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Running the script 
              run:  |
                chmod +x custom.sh
                sh custom.sh
              
    job-3:
        runs-on: ubuntu-latest
        needs: [job-1, job-2]
        steps:
            - name: Generating Dependencies
              run: "This is ran after job-1 and job-2 are finished"                    